# DVC Data Version Control

## 1. Setup Environment

In [1]:
# Cài đặt DVC và thư viện hỗ trợ Google Drive
!pip install dvc dvc[gdrive]

Collecting dvc
  Downloading dvc-3.67.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (25.4.0)
Collecting celery (from dvc)
  Downloading celery-5.6.3-py3-none-any.whl.metadata (23 kB)
Collecting colorama>=0.3.9 (from dvc)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting configobj>=5.0.9 (from dvc)
  Downloading configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: distro>=1.3 in /usr/local/lib/python3.12/dist-packages (from dvc) (1.9.0)
Collecting dpath<3,>=2.1.0 (from dvc)
  Downloading dpath-2.2.0-py3-none-any.whl.metadata (15 kB)
Collecting dulwich (from dvc)
  Downloading dulwich-1.1.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Collecting dvc-data<3.19.0,>=3.18.2 (from dvc)
  Downloading dvc_data-3.18.3-py3-none-any.whl.metadata (4.9 kB)
Collecting dvc-http>=2.29.0 (from dvc)
  Downloading dvc_http-2.32.0-py3-none-any.whl.metadata (1.3 kB)
Collecting dvc-objects (from dvc)
  Downloading dvc_objects-5.2.0-py3-none-any.whl.metadata (3.9 kB)
Collecting dvc-render<2,>=1.0.1 (from dvc)
  Downloading dvc_render-1.0.2-py3-none-any.whl.metadata (5.4 kB)
Collecting dvc-studio-client<1,>=0.21 (from dvc)
  Downloading dvc_studio_client-0.22.0-py3-none-any.whl.metadata (4.4 kB)
Collecting dvc-task<1,>=0.3.0 (from dvc)
  Downloading dvc_task-0.40.2-py3-none-any.whl.metadata (10.0 kB)
Collecting flatten-dict<1,>=0.4.1 (from dvc)
  Downloading flatten_dict-0.4.2-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting flufl.lock<10,>=8.1.0 (from dvc)
  Downloading flufl_lock-9.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: fsspec>=2024.2.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (2025.3.0)
Collecting funcy>=1.14 (from dvc)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting grandalf<1,>=0.7 (from dvc)
  Downloading grandalf-0.8-py3-none-any.whl.metadata (1.7 kB)
Collecting gto<2,>=1.6.0 (from dvc)
  Downloading gto-1.9.0-py3-none-any.whl.metadata (4.9 kB)
Collecting hydra-core>=1.1 (from dvc)
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting iterative-telemetry>=0.0.7 (from dvc)
  Downloading iterative_telemetry-0.0.10-py3-none-any.whl.metadata (4.1 kB)
Collecting kombu (from dvc)
  Downloading kombu-5.6.2-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.6.1)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (from dvc) (2.3.0)
Requirement already satisfied: packaging>=19 in /usr/local/lib/python3.12/dist-packages (from dvc) (26.0)
Collecting pathspec<2,>=0.10.3 (from dvc)
  Downloading pathspec-1.0.4-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: platformdirs<5,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.9.4)
Requirement already satisfied: psutil>=5.8 in /usr/local/lib/python3.12/dist-packages (from dvc) (5.9.5)
Requirement already satisfied: pydot>=1.2.4 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.0.1)
Collecting pygtrie>=2.3.2 (from dvc)
  Downloading pygtrie-2.5.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: pyparsing>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dvc) (3.3.2)
Requirement already satisfied: requests>=2.22 in /usr/local/lib/python3.12/dist-packages (from dvc) (2.32.4)
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.12/dist-packages (from dvc) (13.9.4)
Collecting ruamel.yaml>=0.17.11 (from dvc)
  Downloading ruamel_yaml-0.19.1-py3-none-any.whl.metadata (16 kB)
Collecting scmrepo<4,>=3.5.2 (from dvc)
  Downloading scmrepo-3.6.1-py3-none-any.whl.metadata (4.8 kB)
Collecting shortuuid>=0.5 (from dvc)
  Downloading shortuuid-1.0.13-py3-none-any.whl.metadata (5.8 kB)
Collecting shtab<2,>=1.3.4 (from dvc)
  Downloading shtab-1.8.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.9.0)
Requirement already satisfied: tomlkit>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (0.13.3)
Requirement already satisfied: tqdm<5,>=4.63.1 in /usr/local/lib/python3.12/dist-packages (from dvc) (4.67.3)
Collecting voluptuous>=0.11.7 (from dvc)
  Downloading voluptuous-0.16.0-py3-none-any.whl.metadata (20 kB)
Collecting zc.lockfile>=1.2.1 (from dvc)
  Downloading zc_lockfile-4.0-py3-none-any.whl.metadata (6.6 kB)
Collecting dvc-gdrive<4,>=3 (from dvc[gdrive])
  Downloading dvc_gdrive-3.0.1-py3-none-any.whl.metadata (2.1 kB)
Collecting dictdiffer>=0.8.1 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Downloading dictdiffer-0.9.0-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting diskcache>=5.2.1 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting sqltrie<1,>=0.11.0 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Downloading sqltrie-0.11.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: orjson<4,>=3 in /usr/local/lib/python3.12/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (3.11.7)
Requirement already satisfied: pydrive2>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (1.21.3)
Collecting aiohttp-retry>=2.5.0 (from dvc-http>=2.29.0->dvc)
  Downloading aiohttp_retry-2.9.1-py3-none-any.whl.metadata (8.8 kB)
Collecting billiard<5.0,>=4.2.1 (from celery->dvc)
  Downloading billiard-4.2.4-py3-none-any.whl.metadata (4.8 kB)
Collecting vine<6.0,>=5.1.0 (from celery->dvc)
  Downloading vine-5.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: click<9.0,>=8.1.2 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (8.3.1)
Collecting click-didyoumean>=0.3.0 (from celery->dvc)
  Downloading click_didyoumean-0.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting click-repl>=0.2.0 (from celery->dvc)
  Downloading click_repl-0.3.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: click-plugins>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (1.1.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (2.9.0.post0)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.12/dist-packages (from celery->dvc) (5.3.1)
Requirement already satisfied: six<2.0,>=1.12 in /usr/local/lib/python3.12/dist-packages (from flatten-dict<1,>=0.4.1->dvc) (1.17.0)
Requirement already satisfied: atpublic in /usr/local/lib/python3.12/dist-packages (from flufl.lock<10,>=8.1.0->dvc) (5.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (0.4)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (2.12.3)
Requirement already satisfied: pydantic-settings>=2 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (2.13.1)
Collecting semver>=2.13.0 (from gto<2,>=1.6.0->dvc)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: typer>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gto<2,>=1.6.0->dvc) (0.24.1)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core>=1.1->dvc) (4.9.3)
Collecting appdirs (from iterative-telemetry>=0.0.7->dvc)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from iterative-telemetry>=0.0.7->dvc) (3.25.2)
Collecting amqp<6.0.0,>=5.1.1 (from kombu->dvc)
  Downloading amqp-5.3.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: tzdata>=2025.2 in /usr/local/lib/python3.12/dist-packages (from kombu->dvc) (2025.3)
Requirement already satisfied: PyYAML>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from omegaconf->dvc) (6.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22->dvc) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12->dvc) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12->dvc) (2.19.2)
Requirement already satisfied: gitpython>3 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (3.1.46)
Requirement already satisfied: pygit2>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from scmrepo<4,>=3.5.2->dvc) (1.19.1)
Collecting asyncssh<3,>=2.13.1 (from scmrepo<4,>=3.5.2->dvc)
  Downloading asyncssh-2.22.0-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from zc.lockfile>=1.2.1->dvc) (75.2.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (3.13.3)
Requirement already satisfied: cryptography>=39.0 in /usr/local/lib/python3.12/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (43.0.3)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (4.15.0)
Requirement already satisfied: prompt-toolkit>=3.0.36 in /usr/local/lib/python3.12/dist-packages (from click-repl>=0.2.0->celery->dvc) (3.0.52)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython>3->scmrepo<4,>=3.5.2->dvc) (4.0.12)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12->dvc) (0.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2->gto<2,>=1.6.0->dvc) (1.2.2)
Requirement already satisfied: google-api-python-client>=1.12.5 in /usr/local/lib/python3.12/dist-packages (from pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (2.192.0)
Requirement already satisfied: oauth2client>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (4.1.3)
Requirement already satisfied: pyOpenSSL<=24.2.1,>=19.1.0 in /usr/local/lib/python3.12/dist-packages (from pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (24.2.1)
Requirement already satisfied: cffi>=2.0 in /usr/local/lib/python3.12/dist-packages (from pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (2.0.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.4.1->gto<2,>=1.6.0->dvc) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.4.1->gto<2,>=1.6.0->dvc) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.23.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0->pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (3.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython>3->scmrepo<4,>=3.5.2->dvc) (5.0.3)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (0.31.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (2.47.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (0.3.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (2.30.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (4.2.0)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=4.0.0->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (0.6.3)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=4.0.0->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=4.0.0->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (4.9.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit>=3.0.36->click-repl>=0.2.0->celery->dvc) (0.6.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (1.73.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (1.27.1)
Downloading dvc-3.67.0-py3-none-any.whl (469 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.8/469.8 kB 15.1 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading configobj-5.0.9-py2.py3-none-any.whl (35 kB)
Downloading dpath-2.2.0-py3-none-any.whl (17 kB)
Downloading dvc_data-3.18.3-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 5.8 MB/s eta 0:00:00
Downloading dvc_gdrive-3.0.1-py3-none-any.whl (11 kB)
Downloading dvc_http-2.32.0-py3-none-any.whl (12 kB)
Downloading dvc_objects-5.2.0-py3-none-any.whl (33 kB)
Downloading dvc_render-1.0.2-py3-none-any.whl (22 kB)
Downloading dvc_studio_client-0.22.0-py3-none-any.whl (16 kB)
Downloading dvc_task-0.40.2-py3-none-any.whl (21 kB)
Downloading celery-5.6.3-py3-none-any.whl (451 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 451.2/451.2 kB 25.8 MB/s eta 0:00:00
Downloading flatten_dict-0.4.2-py2.py3-none-any.whl (9.7 kB)
Downloading flufl_lock-9.0.0-py3-none-any.whl (11 kB)
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Downloading grandalf-0.8-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 3.2 MB/s eta 0:00:00
Downloading gto-1.9.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 3.5 MB/s eta 0:00:00
Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 11.3 MB/s eta 0:00:00
Downloading iterative_telemetry-0.0.10-py3-none-any.whl (10 kB)
Downloading kombu-5.6.2-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.2/214.2 kB 15.4 MB/s eta 0:00:00
Downloading vine-5.1.0-py3-none-any.whl (9.6 kB)
Downloading pathspec-1.0.4-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 2.2 MB/s eta 0:00:00
Downloading pygtrie-2.5.0-py3-none-any.whl (25 kB)
Downloading ruamel_yaml-0.19.1-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 7.0 MB/s eta 0:00:00
Downloading scmrepo-3.6.1-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.1/74.1 kB 4.0 MB/s eta 0:00:00
Downloading dulwich-1.1.0-cp312-cp312-manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 28.8 MB/s eta 0:00:00
Downloading shortuuid-1.0.13-py3-none-any.whl (10 kB)
Downloading shtab-1.8.0-py3-none-any.whl (14 kB)
Downloading voluptuous-0.16.0-py3-none-any.whl (31 kB)
Downloading zc_lockfile-4.0-py3-none-any.whl (9.1 kB)
Downloading aiohttp_retry-2.9.1-py3-none-any.whl (10.0 kB)
Downloading amqp-5.3.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 2.1 MB/s eta 0:00:00
Downloading asyncssh-2.22.0-py3-none-any.whl (374 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.9/374.9 kB 13.0 MB/s eta 0:00:00
Downloading billiard-4.2.4-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.1/87.1 kB 2.7 MB/s eta 0:00:00
Downloading click_didyoumean-0.3.1-py3-none-any.whl (3.6 kB)
Downloading click_repl-0.3.0-py3-none-any.whl (10 kB)
Downloading dictdiffer-0.9.0-py2.py3-none-any.whl (16 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 3.5 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading sqltrie-0.11.2-py3-none-any.whl (17 kB)
Installing collected packages: pygtrie, funcy, dictdiffer, appdirs, zc.lockfile, voluptuous, vine, sqltrie, shtab, shortuuid, semver, ruamel.yaml, pathspec, grandalf, flufl.lock, flatten-dict, dvc-render, dvc-objects, dulwich, dpath, diskcache, configobj, colorama, click-didyoumean, billiard, iterative-telemetry, hydra-core, dvc-studio-client, dvc-data, click-repl, amqp, kombu, asyncssh, aiohttp-retry, scmrepo, dvc-http, celery, gto, dvc-task, dvc, dvc-gdrive

In [2]:
!git clone https://github.com/tpdinh2612/sentiment-dvc-code.git
%cd sentiment-dvc-code/
!ls -a

Cloning into 'sentiment-dvc-code'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 23 (delta 3), reused 23 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (23/23), 47.21 KiB | 9.44 MiB/s, done.
Resolving deltas: 100% (3/3), done.
/content/sentiment-dvc-code
.  ..  data  .dvc  .dvcignore  Ex1.pdf	.git

In [3]:
from google.colab import userdata
import os

# Lấy token từ Secrets
dagshub_token = userdata.get('DAGSHUB_TOKEN')

remote_url = "https://dagshub.com/tpdinh2612/sentiment-dvc-data.dvc"
!dvc remote add -d dagshub {remote_url} --force

# Thiết lập cấu hình DVC sử dụng Token này
!dvc remote modify dagshub --local auth basic
!dvc remote modify dagshub --local user tpdinh2612
!dvc remote modify dagshub --local password {dagshub_token}

print("Đã cấu hình DVC với Token từ Secrets thành công!")

Setting 'dagshub' as a default remote.
Đã cấu hình DVC với Token từ Secrets thành công!

## 2.  Retrieving data on another machine

In [4]:
!dvc pull

Collecting          |1.00 [00:00, 83.5entry/s]
Fetching
!
  0% |          |0/? [00:00<?,    ?files/s]

!
  0% |          |0/? [00:00<?,    ?files/s]
100% 1/1 [00:00<00:00,  1.68files/s{'info': ''}]

Fetching from https:   0% 0/1 [00:00<?, ?file/s]
Fetching from https:   0% 0/1 [00:00<?, ?file/s{'info': ''}]

!

          |0.00 [00:00,        ?B/s]


Fetching from https: 100% 1/1 [00:00<00:00,  2.17file/s{'info': ''}]
Fetching
Building workspace index          |2.00 [00:00, 80.4entry/s]
Comparing indexes          |4.00 [00:00, 1.03kentry/s]
Applying changes          |1.00 [00:00,   160file/s]
A       data/raw/sentiment.csv
1 file fetched and 1 file added

Sau khi pull về, trong thư mục data/raw/ sẽ xuất hiện file **sentiment.csv**

In [5]:
import pandas as pd

# Đường dẫn tới file csv dựa trên thư mục của bạn
file_path = 'data/raw/sentiment.csv'

# Đọc file csv vào DataFrame
df = pd.read_csv(file_path)

# Hiển thị 5 dòng đầu tiên để kiểm tra
display(df)

                    text     label
0      I love this movie  positive
1      This was terrible  negative
2    Pretty good overall  positive
3          Waste of time  negative
4  An amazing experience  positive
5     Not worth watching  negative
6    Fantastic storyline  positive

## 3. List versions

In [6]:
# Xem lịch sử các lần commit liên quan đến file .dvc của dữ liệu
!git log --oneline data/raw/sentiment.csv.dvc

d0526f2 (HEAD -> master, origin/master, origin/HEAD) Dataset v2: add more rows
76527e6 Track sentiment dataset v1

## 4. Switch between versions

In [7]:
# Thay mã hash commit
hash_commit = "76527e6"
!git checkout {hash_commit} data/raw/sentiment.csv.dvc

Updated 1 path from 2aaf2d9

Vì:
- Git chỉ quản lý và lưu trữ metadata (các file code, file .dvc). Git hoàn toàn không chứa dữ liệu lớn thực tế.

- DVC lưu trữ dữ liệu lớn thực tế (dataset, file model .pt, .h5, ...) bên trong thư mục bộ nhớ đệm cục bộ (.dvc/cache) hoặc trên máy chủ từ xa (Remote Storage như S3, Google Drive)

Nên sau khi git checkout version cũ thành công, git chỉ đổi file .dvc, cần chạy `dvc pull` để tải dữ liệu từ Remote Storage.

In [8]:
!dvc pull

Collecting          |1.00 [00:00,  115entry/s]
Fetching
!
  0% |          |0/? [00:00<?,    ?files/s]

!
  0% |          |0/? [00:00<?,    ?files/s]
100% 1/1 [00:00<00:00,  6.04files/s{'info': ''}]

Fetching from https:   0% 0/1 [00:00<?, ?file/s]
Fetching from https:   0% 0/1 [00:00<?, ?file/s{'info': ''}]

!

          |0.00 [00:00,        ?B/s]


Fetching from https: 100% 1/1 [00:00<00:00,  4.93file/s{'info': ''}]
Fetching
Building workspace index          |3.00 [00:00,  111entry/s]
Comparing indexes          |4.00 [00:00, 1.06kentry/s]
Applying changes          |1.00 [00:00,   186file/s]
M       data/raw/sentiment.csv
1 file fetched and 1 file modified

In [9]:
!dvc checkout

Building workspace index          |3.00 [00:00, 20.4entry/s]
Comparing indexes          |4.00 [00:00, 1.02kentry/s]
Applying changes          |0.00 [00:00,     ?file/s]

In [10]:
# In ra kiểm tra
file_path = 'data/raw/sentiment.csv'
df = pd.read_csv(file_path)
display(df)

                  text     label
0    I love this movie  positive
1    This was terrible  negative
2  Pretty good overall  positive
3        Waste of time  negative

Vậy là đã switch qua được data version trước thành công!